[phases.setup]
nixPkgs = ['python310','glibc']
aptPkgs = ['...','libsm6','wget','libc6','alien','libaio1','libnss3','libnss3-tools','libnss3-dev','libnss3-1d']

cmds = [
  'sudo apt-get -y update',
  'wget https://download.oracle.com/otn_software/linux/instantclient/2340000/instantclient-basiclite-linux.x64-23.4.0.24.05.zip',
  'unzip instantclient-basiclite-linux.x64-23.4.0.24.05.zip',
  'cd instantclient_23_4',
  'ln -s libclntsh.so.2.1 libclntsh.so',
  'ln -s libocci.so.22.1 libocci.so',
  'cd ..',
  "ls",
  "sudo sh -c 'echo /instantclient_23_4 > /etc/ld.so.conf.d/oracle.conf'",
  'sudo ldconfig',
  'echo "Everything OK ----------------------------------"',
]