[phases.setup]
nixPkgs = ['python310','glibc']
aptPkgs = ['...','libsm6','wget','unzip','libc6','alien','libaio1']

cmds = [
  'sudo apt-get -y update',
  'wget https://download.oracle.com/otn_software/linux/instantclient/2340000/instantclient-basiclite-linux.x64-23.4.0.24.05.zip',
  'unzip instantclient-basiclite-linux.x64-23.4.0.24.05.zip',
  'cd instantclient_23_4',
  'ln -s instantclient_23_4/libclntsh.so.22.1 instantclient_23_4/libclntsh.so',
  'ln -s instantclient_23_4/libocci.so.22.1 instantclient_23_4/libocci.so',
  'cd ..',
  "echo ls",
  "sudo sh -c 'echo /instantclient_23_4 > /etc/ld.so.conf.d/oracle.conf'",
  'sudo ldconfig',
  'echo "Everything OK ----------------------------------"',
]