[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
numReplicas = 1
startCommand = "gunicorn --worker-class=gevent --worker-connections=1000 --workers=3 api:app"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10